# .github/workflows/ci.yml
name: Hardhat CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: hardhat-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      HARDHAT_NETWORK: hardhat
      NODE_OPTIONS: --test-reporter=spec
      # Expose to Hardhat config (compile/test won't need them, deploy will)
      RPC_URL: ${{ secrets.RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      # optional if your RPC needs it; use Actions "Variables" if non-secret:
      CHAIN_ID: ${{ vars.CHAIN_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'               # Hardhat v3+ wants Node 22 LTS
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Compile
        run: npx hardhat compile

      # TS + ESM tests (your Counter test)
      - name: Run node:test (TypeScript, ESM)
        run: node --loader ts-node/esm --test "test/**/*.ts" "test/*.ts"

      # Fail early if secrets missing on main
      - name: Verify deploy env
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          [ -n "${RPC_URL}" ] || { echo "RPC_URL is not set"; exit 1; }
          [ -n "${PRIVATE_KEY}" ] || { echo "PRIVATE_KEY is not set"; exit 1; }
          echo "Deploy env OK."

      - name: Deploy (didlab)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: npx hardhat run scripts/deploy2.ts --network didlab

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hardhat-artifacts
          path: |
            artifacts
            cache
