name: Hardhat CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: hardhat-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      HARDHAT_NETWORK: hardhat
      NODE_OPTIONS: --test-reporter=spec

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Compile contracts
        run: npx hardhat compile

      # Optional legacy mocha-style tests (kept non-fatal)
      - name: Run Hardhat (Mocha) tests (optional)
        run: |
          if ls test 1>/dev/null 2>&1 && grep -RIlq "" test 2>/dev/null; then
            npx hardhat test || true
          fi

      # --- The important part for TS + ESM + node:test ---
      - name: Run node:test (TypeScript, ESM)
        run: |
          # Requires devDependency: ts-node >= 10.9
          node --loader ts-node/esm --test "test/**/*.ts" "test/*.ts"

      # Deploy only on push to main (not PRs)
      - name: Deploy contracts
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
        run: |
          echo "Deploying with scripts/deploy2.ts to 'didlab'..."
          npx hardhat run scripts/deploy2.ts --network didlab

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hardhat-artifacts
          path: |
            artifacts
            cache
