# .github/workflows/ci.yml
name: Hardhat CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: hardhat-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: CICD     

    env:
      HARDHAT_NETWORK: hardhat
      NODE_OPTIONS: --test-reporter=spec
      # read from the environment's secrets/vars
      RPC_URL: ${{ secrets.RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      CHAIN_ID: ${{ secrets.CHAIN_ID || vars.CHAIN_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Compile
        run: npx hardhat clean && npx hardhat compile --force

      - name: Run tests (Hardhat)
        run: npx hardhat test

      - name: Verify deploy env
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          [ -n "${RPC_URL}" ] || { echo "RPC_URL is not set"; exit 1; }
          [ -n "${PRIVATE_KEY}" ] || { echo "PRIVATE_KEY is not set"; exit 1; }
          echo "Deploy env OK."

      - name: Deploy (didlab)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          RPC_URL:     ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CHAIN_ID:    ${{ secrets.CHAIN_ID }}
          # Token params (set in the CICD environment as Secrets/Variables)
          TOKEN_NAME:       ${{ vars.TOKEN_NAME || secrets.TOKEN_NAME }}
          TOKEN_SYMBOL:     ${{ vars.TOKEN_SYMBOL || secrets.TOKEN_SYMBOL }}
          TOKEN_CAP:        ${{ vars.TOKEN_CAP || secrets.TOKEN_CAP }}
          INITIAL_MINT:     ${{ vars.INITIAL_MINT || secrets.INITIAL_MINT }}
          INITIAL_RECEIVER: ${{ vars.INITIAL_RECEIVER || secrets.INITIAL_RECEIVER }}
          MAX_FEE_GWEI: ${{ vars.MAX_FEE_GWEI || secrets.MAX_FEE_GWEI }}
          # Tell the script which contract to deploy:
          CONTRACT_NAME: BankMintToken
        run: npx hardhat run scripts/deploy2.ts --network didlab

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hardhat-artifacts
          path: |
            artifacts
            cache
